# Group Members
# (1) Collin DeMatt
# (2) Adam Geiger
# (3) Mike Rabbitz

driver: main.o 
	g++ -o main main.o -std=c++11

main.o: main.cpp memoryManager.hpp virtualMemoryManagerInterface.hpp
	g++ -c main.cpp -std=c++11
